spring:
  datasource:
    url: jdbc:postgresql://localhost:54329/student
    username: student
    password: student
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  application:
    name: students
server:
  port: 8081
